version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
          working_directory: ~/project/my-app
      - restore_cache:
          key: circleci-java-maven-{{ checksum "/tmp/maven_cache_seed" }}
      - run:
          command: mvn package
          working_directory: ~/project/my-app
      - save_cache:
          paths:
            - ~/.m2/repository
          key: circleci-java-maven-{{ checksum "/tmp/maven_cache_seed" }}
      - run:
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
          path: ~/project/my-app/target/my-app-1.0-SNAPSHOT.jar

workflows:
  sample:
    jobs:
      - build-and-test
