version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
          working_directory: ~/project/my-app
      - restore_cache:
          key: circleci-java-maven-{{ checksum "/tmp/maven_cache_seed" }}
      - run:
          command: mvn jacoco:prepare-agent package jacoco:report
          working_directory: ~/project/my-app
      - save_cache:
          paths:
            - ~/.m2/repository
          key: circleci-java-maven-{{ checksum "/tmp/maven_cache_seed" }}
      - run:
          command: |
            mkdir -p ~/artifacts/junit/
            mkdir -p ~/artifacts/jar/
            mkdir -p ~/artifacts/reports/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/artifacts/junit/ \;
            cp ~/project/my-app/target/my-app-1.0-SNAPSHOT.jar ~/artifacts/jar/
            cp ~/project/my-app/target/jacoco.exec ~/artifacts/reports/
          when: always
      - store_test_results:
          path: ~/artifacts/junit/
      - store_artifacts:
          path: ~/artifacts

workflows:
  sample:
    jobs:
      - build-and-test
